---
- name: Make sure that the alexandria path exists
  file:
    path: "{{ upload_alexandria_path }}"
    state: directory

- name: Create alexandria systemd service
  become: yes
  template:
    src: alexandria.service
    dest: /etc/systemd/system/alexandria.service

- name: Reload systemd config
  become: yes
  command: systemctl daemon-reload

- name: Upload config file
  include: upload_config_file.yml

- name: Upload alexandria jar and reload
  include: upload_alexandria_jar.yml
