---
- name: add PostgreSQL apt repository key
  become: true
  apt_key:
    id: "{{ postgres_repo_key }}"
    url: "{{ postgres_repo_key_url }}"

- name: add PostgreSQL apt repository
  become: true
  apt_repository:
    repo: "{{ postgres_repo_url }}"

- name: install PostgreSQL server
  become: true
  apt:
    name: postgresql-9.5
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: copy pg_hba.conf
  become: true
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/9.5/main/pg_hba.conf
  notify:
    - restart postgresql
