---
- name: add openjdk-8 repo
  become: true
  apt_repository:
    repo: "{{ java_repo_url }}"
    state: present

- name: install openjdk-8
  become: true
  apt:
    pkg: openjdk-8-jdk
    state: installed
    update_cache: true
